application: gerrit-code-review-tool-demo
version: 1
runtime: python
api_version: 1

default_expiration: 7d  # This is good for images, which never change

handlers:

- url: /(robots.txt|favicon.ico)
  static_files: static/\1
  upload: static/(robots.txt|favicon.ico)

- url: /google7db36eb2cc527940.html
  static_files: static/robots.txt
  upload: static/robots.txt

- url: /(application_version)
  static_files: static/\1
  mime_type: text/plain
  expiration: 1s
  upload: static/application_version

- url: /static
  static_dir: static

- url: .*
  script: main.py
