application: gerrit-documentation
version: 1
runtime: python
api_version: 1

default_expiration: 5m

handlers:
- url: /application_version
  mime_type: text/plain
  static_files: application_version
  upload: application_version

- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico

- url: /Documentation
  static_dir: Documentation

- url: .*
  script: redirect.py
